name: Docker Workflow

on:
  - push
  
jobs: 
  docker_build: 
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Build 
      run: docker build -t resume-app:latest .

    - name: Docker Login
      run: docker login --username=efotsowoe --password=ricewater!!233

    - name: Docker Publish 
      run: docker push docker.io/efotsowoe/resume:latest

  docker_deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Docker Run
        run: docker run -d -p 8080:80 docker.io/efotsowoe/resume:latest